### ISSUE TITLE
Standardize return when a word or template isn't found

### ISSUE THREAD

**Issue by jonathanbratt** [jonthegeek/wikimorphemes#10]
In the various word/wikitext processing functions, we have to return something when the word or template isn't found. Decide on what to return. 
Some candidates:
 - NA_character 
 - character(0)
 - [if the word is available] the input word

**Comment by jonathanbratt** [comment]
Also, note that the "template not found" case is not always handled explicitly. If a template regex isn't found, this results in NAs that might get processed into character(0) in further steps. So whatever we decide upon will need to be enforced by checking for edge cases more explicitly than is being done now.

**Comment by jonthegeek** [comment]
I'm tempted to just return the word, but this might break morphemepiece. Still, I think that's more valid for most use cases. Right now, if someone sends us a fake word to break into pieces, we return `character(0)`, and it seems like that would be unexpected.

**Comment by jonthegeek** [comment]
Ok, in the end we return the word. Some unexported functions could have edge-case behavior, but, in the end, it'll be the word, unbroken.
