### ISSUE TITLE
wiktionary dump from 04/09 on datascience is missing many (most) words

### ISSUE THREAD

**Issue by jonathanbratt** [jonthegeek/wikimorphemes#24]
Some specific words that are missing: "world", "conservation".

**Comment by jonthegeek** [comment]
Fixed on our server. Wrapping up the code and figuring out where/how to share before I close this out.

**Comment by jonathanbratt** [comment]
@jonthegeek can we close this issue now?

**Comment by jonthegeek** [comment]
https://data.world/jonthegeek/wikimorphemes
